name = "xugou-backend"
main = "src/index.ts"
compatibility_date = "2025-03-10"
compatibility_flags = ["nodejs_compat"]

# 添加定时触发器，每分钟执行一次监控检查
[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "tanz"
database_id = "0ebd2c8b-962c-4faf-9712-8f8c66d6df66"

[version_metadata]
binding = "CF_VERSION_METADATA"
